### ISSUE TITLE
InstallDotNetAgent.ps1

### ISSUE THREAD

**Issue by amarlot** [Dynatrace/Dynatrace-Powershell#1]
Hi Team,

I think there is a bug in InstallDotNetAgent.ps1. Indeed you check if req equals 0 and just after you check if req is equals to 1.

I think in the first if it's -ne no ?

Thanks,
Alex

$res = Test-DotNETAgentInstallation
if ($res -eq 0)
{
    if ($res -eq 1)

**Comment by dtPaTh** [comment]
Thank you  - your pullrequest is already committed.
