### ISSUE TITLE
$ServiceName = "Dynatrace Webserver Agent" ??

### ISSUE THREAD

**Issue by amarlot** [Dynatrace/Dynatrace-Powershell#3]
Hi Team,

We are running Dynatrace 6.1.3 and it seems the agent name is now "dynaTrace Web Server Agent 6.1.0" and not anymore : "Dynatrace Webserver Agent"

So it doesn't create/restart the good service.

What do you think ?
Thanks,
Alex

**Comment by dtPaTh** [comment]
Hi Alex, 

as the modules & scripts are not version specific, i kept names clean, which made it much easier to handle the service. Unfortunately this makes the scripts not directly compatible when mixing up with deployments created using the installer. 

If you plan to stick with the powershell scripts in future i recommend to re-register the service. For this case you can use functions of modules/InstallWebserverAgent.psm1 where you can unregister the service with the name used by the installer. 

Does that work for you?
Patrick

**Comment by amarlot** [comment]
Hi Patrick,

Thanks. It's clear. Indeed we did a mix between the windows installer and your script.

You can close this ticket.
Alex
